name: Nightly

on:
  schedule:
    - cron: "0 4 * * *"

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

jobs:
  ####################
  # Linux / macOS
  ####################

  Unix:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        config: [Release]
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-18.04
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install \
          libboost-filesystem-dev \
          libboost-system-dev \
          ccache

      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install boost ccache gmp

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.config }}-cache

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCCD_WRAPPER_IS_CI_BUILD=ON \

      - name: Build
        run: cd build; make -j2; ccache --show-stats

      - name: Tests
        run: cd build; ctest --verbose --output-on-failure

      - name: Sample Benchmark
        run: cd build; ./CCDBenchmark

  ####################
  # Windows
  ####################

  Windows:
    name: Windows (${{ matrix.config }})
    runs-on: windows-2019
    env:
      CC: cl.exe
      CXX: cl.exe
      SCCACHE_IDLE_TIMEOUT: "12000"
    strategy:
      fail-fast: false
      matrix:
        config: [Release]
    steps:
      - name: Stetup Conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: anaconda, conda-forge
          python-version: 3.6

      - name: Install Dependencies
        shell: powershell
        run: |
          conda install -c conda-forge mpir -y

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - uses: seanmiddleditch/gha-setup-ninja@master
        # https://github.com/actions/cache/issues/101
      - name: Set env
        run: |
          echo "::set-env name=appdata::$($env:LOCALAPPDATA)"
          echo "::set-env name=GMP_INC::C:\Miniconda\Library\include"
          echo "::set-env name=GMP_LIB::C:\Miniconda\Library\lib"
          echo "::set-env name=BOOST_ROOT::$($env:BOOST_ROOT_1_72_0)"

      - name: Cache build
        id: cache-build
        uses: actions/cache@v1
        with:
          path: ${{ env.appdata }}\Mozilla\sccache
          key: ${{ runner.os }}-${{ matrix.config }}-cache

      - name: Prepare sccache
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install sccache --global
          # Scoop modifies the PATH so we make the modified PATH global.
          echo "::set-env name=PATH::$env:PATH"

      - name: Configure and build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake --version
          cmake -G Ninja ^
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ^
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} ^
            -DCCD_WRAPPER_IS_CI_BUILD=ON ^
            -DCCD_WRAPPER_WITH_MSRF=OFF ^
            -B build ^
            -S .
          cd build
          ninja -j1

      - name: Tests
        run: |
          cd build
          cp C:\Miniconda\Library\bin\mpir.dll .\
          cp C:\Miniconda\Library\bin\gmp.dll .\
          ctest --verbose --output-on-failure
      - name: Sample Benchmark
        shell: powershell
        run: |
          cd build
          cp C:\Miniconda\Library\bin\mpir.dll .\
          cp C:\Miniconda\Library\bin\gmp.dll .\
          .\CCDBenchmark.exe
